In [1]:
import pandas as pd
import csv

In [2]:
ufo_df = pd.read_csv('UFO_data.csv', index_col=False,low_memory=False)
ufo_df

,Description,Shape,Duration,City,State,Date,Time,Latitude,Longitude
0,Viewed some red lights in the sky appearing to...,light,2 minutes,Visalia,CA,12/15/2021,21:45:00,36.356650,-119.347937
1,Look like 1 or 3 crafts from North traveling s...,triangle,14 seconds,Cincinnati,OH,12/16/2021,9:45:00,39.174503,-84.481363
2,"One red light moving switly west to east, beco...",triangle,20-30 seconds,Knoxville,TN,12/10/2021,19:30:00,35.961561,-83.980115
3,I'm familiar with all the fakery and UFO sight...,unknown,2 minutes,Fullerton,CA,7/7/2020,23:00:00,33.877422,-117.924978
4,I was driving up lakes mead towards the lake a...,oval,10 minutes,Las Vegas,NV,4/23/2020,3:00:00,36.141246,-115.186592
...,...,...,...,...,...,...,...,...,...
93529,group of 7 white flashing and disappearing fly...,sphere,5 minutes,Nashville,TN,11/9/2019,14:00:00,36.131700,-86.776813
93530,"Bright light at high altitude, looked like a l...",light,10-15 minutes,Snyder,TX,1/10/2009,0:30:00,32.891660,-100.914816
93531,This object was disc shaped and parked frozen ...,disk,5 minutes,Houston,TX,8/30/2011,19:35:00,29.777494,-95.451220
93532,Cloaked light disc pretends to be a cloud form...,disk,15 minutes,Portland,OR,9/20/2012,13:00:00,45.510530,-122.665204
93533,6 red flashing lights in the sky over North GA...,light,35 seconds,Cumming,GA,12/12/2012,22:30:00,34.179411,-84.140295